version: '3.6'
services:
  postgres:
    image: postgres:14.5
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=3GB"
      - "-c"
      - "effective_cache_size=12GB"
      - "-c"
      - "work_mem=32MB"
      - "-c"
      - "maintenance_work_mem=1GB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=5GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: grafana
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: e366311e-828a-4433-862e-0cc20bcf197c
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./create_extensions.sql:/docker-entrypoint-initdb.d/create_extensions.sql:ro
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U grafana"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - monitoring
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 12G

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.11.1
    command: --log.level=debug
    environment:
      DATA_SOURCE_URI: "postgres:5432/grafana?sslmode=disable"
      DATA_SOURCE_USER: grafana
      DATA_SOURCE_PASS: e366311e-828a-4433-862e-0cc20bcf197c
      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
    volumes:
      - ./queries.yaml:/etc/postgres_exporter/queries.yaml:ro
    ports:
      - '9187:9187'
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  monitoring:
    name: monitoring
